platform :ios, '12.0'
use_frameworks!

target 'AstroForms_Example' do
  pod 'AstroForms', :path => '../'

  target 'AstroForms_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
